defmodule SurfacePlaygroundWeb.Components.Gauge do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.Component

  # import SurfacePlaygroundWeb.Gettext

  @doc "The name"
  prop name, :any

  def render(assigns) do
    ~F"""
    <meter/>
    """
  end
end
