defmodule SurfacePlaygroundWeb.Components.Gauge do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.Component

  # import SurfacePlaygroundWeb.Gettext

  @doc "The name"
  prop name, :any

  @doc "ID of the gauge"
  prop id, :string

  @doc "Extra options for the gauge"
  prop opts, :keyword, default: []

  def render(assigns) do
    ~F"""
    <meter id={@id} name={@name} :attrs={@opts}/>
    """
  end
end
