defmodule SurfacePlaygroundWeb.Components.Slider do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.Component

  # import SurfacePlaygroundWeb.Gettext

  @doc "The field name"
  prop name, :any

  def render(assigns) do
    ~F"""
    <div>
    PUT SLIDER HERE
    </div>
    """
  end
end
